### ISSUE TITLE
Does't jump when clicking superlinks for header (the part above 'expand/collapse all')

### ISSUE THREAD

**Issue by 0xNi** [kaiiiz/hexo-theme-book#7]
The example website of author works well, but i get this problem. How can I fix this?

**Comment by xieyuheng** [comment]
Please, provide your code, and describe how to re-produce the bug.

**Comment by 0xNi** [comment]
Sorry for the unclear description.

This is one article of my blog: [link](https://0xni.github.io/2018/03/18/more-memory-timings/)

The markdown file looks like:

```
# 基本时序
## CAS Latency （CL）
...
## RAS to CAS Delay（tRCD）
...
```

I use the automatically generated `archive` of hexo for one of entry of menu. 

Besides, I found that if the markdown files are not put in the folder `_posts`, the contents for header of the right side doesn't show at all. (I tried to put this file into another folder in `source` rather than `_posts`) I guess maybe there are some plugins I need to install.

For me, I only follow the instructions and do these operations.

```
npm install hexo-renderer-scss --save
npm uninstall hexo-renderer-marked --save
npm install hexo-renderer-markdown-it --save
```

```
hexo  -v
hexo: 3.9.0
hexo-cli: 3.1.0
os: Linux 5.0.0-36-generic linux x64
node: 13.2.0
v8: 7.9.317.23-node.20
uv: 1.33.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 79
nghttp2: 1.40.0
napi: 5
llhttp: 1.1.4
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019c
unicode: 12.1
```
```
npm -v
6.13.1
```


P.S. The `expand/collapse all` button doesn't work as well

**Comment by 0xNi** [comment]
I just find that, using one other [theme](https://github.com/Siricee/hexo-theme-Chic) shows same problem.

The TOC in theme chic looks like same with yours.

**Comment by xieyuheng** [comment]
> markdown files are not put in the folder `_posts`

.md files should be putted in `_posts`.

where is your source code?
this repo only contain the generated html files: https://github.com/0xNi/0xNi.github.io

**Comment by kaiiiz** [comment]
@0xNi Do you config `anchors` options in theme's `_config.yml` ?

```
markdown:
  render:
    html: true # Doesn't escape HTML content so the tags will appear as html.
    xhtmlOut: false # Parser will not produce XHTML compliant code.
  ...
  anchors:
    # Minimum level for ID creation. (Ex. h2 to h6)
    level: 1
    # A suffix that is prepended to the number given if the ID is repeated.
    collisionSuffix: 'v'
    # If `true`, creates an anchor tag with a permalink besides the heading.
    permalink: false
    # Class used for the permalink anchor tag.
    permalinkClass: header-anchor
    # The symbol used to make the permalink
    permalinkSymbol: '# '
```

These settings will generate anchors for toc link.

After config these settings, use `hexo clean` and `hexo server` to check again.

PS. `Expand all` only work if the depth of toc more than 2 level, check https://kaiiiz.github.io/hexo-theme-book-demo/demo/markdown-it-demo/ for more detail.
